export const blogList = [
  {
    id: 1,
    authorName: 'TraderBrunotte',
    authorAvatar: '/assets/images/authorStefanBlack.png',
    
    instrumentCoverImage: '/assets/images/ES/17012023_Tuesday_ES0323.jpg',
    tradingDate: 'Tuesday January 17, 2023',
    title: 'ES 03-23 | 17:25-18:55 | +4,25 points ',
    category: 'ES',
    subCategory: ['ES 03-23'],

    numOfTrades: "7",
    totalPoints: "4,25",
    totalTicks: "17",
    winners: "4 (4 points)",
    losers: "2 (-2,75 points)",
    breakEven: "1 (0,25 points)",
    NumOfTarget: "4 out of 7",

    tradeDescription: "This is the first session where I have traded with my new 1-tick scalping method. The basic setup is that I enter the market after and on the close of a trigger bar. I always need a signal bar that closes within the 75% upper range in an uptrend or closes within the lower 25% of the signal bar range. I may only enter if the signal bar is a 100% high-, or low-closing bar, if this happens I may enter early and take a chance.",
    summary: "The lesson to be learned from this session is that I can take a chance and enter at the close of a strong signal bar closing on its high or low (100%)! The bulls/bears are clearly in control and there is a high probability of at least 1 point up/down on the trigger bar. This is the only time I may enter with a signal bar! I would have made 5 winners and 2 losers if I had entered long on the high closing 100% bull signal bars and low closing 100% bear signal bars.",
    trade1Header:"Trade 1, Long, Hit +1 point target",
    reasonToTakeTrade1: "Reason to enter: acceptance above previous swing high, ie confirmed bull trend, strong signal bar (100%) and trigger bar.",
    trade1: "Market was in an uptrend after breaking and closing above the swing high, there was a small pullback with a strong signal bar (closing on its high - 100%). I entered at the close of the trigger bar and got filled straight away. The market quickly rallied up to my target for a 1 tick profit with a very small risk!",

    trade2Header:"Trade 2, Long, Stopped out -1 point",
    reasonToTakeTrade2: "Reason to enter: Strong signal bar after pullback in bull trend.",
    trade2: "The market gave another strong signal bar (closing on its high -100%). I missed the entry at the trigger bar high but went long a little bit lower, I got scared and moved my stop closer and got stopped out by 2 ticks, should have waited for the bear bar to close and then trail my stop!",

    trade3Header:"Trade 3, Long, Break-even +0,25 points",
    reasonToTakeTrade3: "Reason to enter: Strong signal bar (100%) after failed bear breakout below earlier sideways market.",
    trade3: "The market gave another great signal bar (closing on its high -100%). The market touched my target and my trailing stop was triggered and was moved to break-even +1, I didn’t get filled at target and I was stopped out. This trade was just bad luck, target should have been reached but there were strong bears that tested the bulls.",

    trade4Header:"Trade 4, Long, Hit +1 point target",
    reasonToTakeTrade4: "Reason to enter: Signal bar close above previous highs, third leg of bull trend up to older resistance.",
    trade4: "I entered at the close of the trigger bar after the market gave me a weaker signal bar (80%). Target was reached and it tested the previous high of the bear leg down before the session start. This was also the high of my session.",

    trade5Header:"Trade 5, Short, Stopped out -1,75 points",
    reasonToTakeTrade5: "Reason to enter: Strong close below previous swing low and confirmation of bear trend.",
    trade5: "The market gave me two weak bear signal bars, but the move down was strong. I entered short after bear trend confirmation (close below previous swing low) and was stopped out almost at my full stop (8 ticks). I should have waited for the pullback before entering the market, there was a strong leg down and I entered at the end of the first leg down (should have waited).",

    trade6Header:"Trade 6, Short, Hit +1 point target",
    reasonToTakeTrade6: "Reason to enter: Trigger bar after small one-bar pullback.",
    trade6: "The doji bar was the signal bar (80%), I entered short at the close of the trigger bar. The trade was a bit long (1:43 min) because the bulls tried to push the market back up. This was a good trade because the probability of more down was high after the strong first bear leg down. ",

    trade7Header:"Trade 7, Long, Hit +1 point target",
    reasonToTakeTrade7: "Reason to enter: Double bottom after strong bull leg down.",
    trade7: "This was a counter trend long after a strong bull signal bar (100%) I was filled after the close of the trigger bar (which ended up as another strong signal bar 100%). I reached target after 1:12 seconds.",

    trade8Header:"",
    reasonToTakeTrade8: "",
    trade8: "",
    trade9Header:"",
    reasonToTakeTrade9: "",
    trade9: "",
    trade10Header:"",
    reasonToTakeTrade10: "",
    trade10: "",
    trade11Header:"",
    reasonToTakeTrade11: "",
    trade11: "",
    trade12Header:"",
    reasonToTakeTrade12: "",
    trade12: "",
    trade13Header:"",
    reasonToTakeTrade13: "",
    trade13: "",
    trade14Header:"",
    reasonToTakeTrade14: "",
    trade14: "",
    trade15Header:"",
    reasonToTakeTrade15: "",
    trade15: "",
    trade16Header:"",
    reasonToTakeTrade16: "",
    trade16: "",
    trade17Header:"",
    reasonToTakeTrade17: "",
    trade17: "",
  },
  {
    id: 2,
    authorName: 'TraderBrunotte',
    authorAvatar: '/assets/images/authorStefanBlack.png',
    
    instrumentCoverImage: '/assets/images/ES/18012023_Wednesday_ES0323.jpg',
    tradingDate: 'Wednesday January 18, 2023',
    title: 'ES 03-23 | 15:30-15:45 | -8 points ',
    category: 'ES',
    subCategory: ['ES 03-23'],

    numOfTrades: "4",
    totalPoints: "-8",
    totalTicks: "-16",
    winners: "2 (2 points)",
    losers: "2 (-4 points)",
    breakEven: "0",
    NumOfTarget: "2 out of 4",

    tradeDescription: "The market move very fast, 1597 ticks was way to small for me to trade. I am not able to make good decisions when the market is this fast, the longest trade took 16 seconds! I need to stay away from these conditions and wait for more direction, up or down.",
    summary: "First session of the day, took a small break because I was not able to make good trade decisions in this fast moving market! The market moved to fast for me in the early session, 1597 ticks is too small and I need to move up to a 2000 tick chart and I should also avoid these sideways market, better to wait for some direction before I start to trade. Longest time I was in the market was 16 seconds! Very fast market and very hard to make good decisions! I must trade more ticks when the market is behaving like this!",
    trade1Header:"Trade 1, short, hit +1-point target",
    reasonToTakeTrade1: "Reason to enter: Strong bear signal bar (100%)",
    trade1: "Market made a lower high and I entered at the close of the signal bar (100%), the market was moving to fast for me so I did not have control. The trade hit target but is not a good trade in hindsight because of the sideways context of the market. It was a breakout below a double bottom. I should never sell at the bottom of a sideways market.",

    trade2Header:"Trade 2, short, hit +1-point target",
    reasonToTakeTrade2: "Reason to enter: Slipped with my fingers! ",
    trade2: "Lucky result, I don’t count this trade!",

    trade3Header:"Trade 3, Long, full stop (-2 points)",
    reasonToTakeTrade3: "Reason to enter: Strong leg up and missed opportunities (bad price read!) ",
    trade3: "The market was in a sideways market, and I bought at the top of the sideways market, bad price read, and I shouldn’t have entered, I got a full stop and lost all profit from the two previous trades.",

    trade4Header:"Trade 4, Long, full stop (-2 points)",
    reasonToTakeTrade4: "Reason to enter: Strong leg down in sideways market",
    trade4: "Another sell at the bottom of the sideways market! Strong leg down but I may not sell at the bottom of the sideways market, I need to get more direction before trading.",

    trade5Header: "",
    reasonToTakeTrade5: "",
    trade5: "",
    trade6Header:"",
    reasonToTakeTrade6: "",
    trade6: "",
    trade7Header:"",
    reasonToTakeTrade7: "",
    trade7: "",
    trade8Header:"",
    reasonToTakeTrade8: "",
    trade8: "",
    trade9Header:"",
    reasonToTakeTrade9: "",
    trade9: "",
    trade10Header:"",
    reasonToTakeTrade10: "",
    trade10: "",
    trade11Header:"",
    reasonToTakeTrade11: "",
    trade11: "",
    trade12Header:"",
    reasonToTakeTrade12: "",
    trade12: "",
    trade13Header:"",
    reasonToTakeTrade13: "",
    trade13: "",
    trade14Header:"",
    reasonToTakeTrade14: "",
    trade14: "",
    trade15Header:"",
    reasonToTakeTrade15: "",
    trade15: "",
    trade16Header:"",
    reasonToTakeTrade16: "",
    trade16: "",
    trade17Header:"",
    reasonToTakeTrade17: "",
    trade17: "",
  },
  {
    id: 3,
    authorName: 'TraderBrunotte',
    authorAvatar: '/assets/images/authorStefanBlack.png',
    
    instrumentCoverImage: '/assets/images/6E/20012023_Friday_6E.jpg',
    tradingDate: 'Friday January 20, 2023',
    title: '6E | 10:00-11:30 | +16 ticks ',
    category: '6E',
    subCategory: ['6E 03-23'],

    numOfTrades: "2",
    totalPoints: "1.8",
    totalTicks: "-",
    totalPips: "+16",
    winners: "2",
    losers: "0",
    breakEven: "0",
    NumOfTarget: "2 out of 2",

    tradeDescription: "First 6E (forex futures) session. I traded the early London session before lunch, I got two trades that hit target. I used my three contract scalping strategy and my target for each trade was $150. The early London session was quite slow which was good for me, I was able to think over my entries and did not have to rush into them. I missed an opportunity at the end of my session.",
    summary: "Morning London session, I trade the 6E market (forex futures). The market was in a bear trend after making the high of the day earlier. I took two trades that each made target without any problem. The market was quite slow and this makes it easier to analyse the market better. I’m happy with my trades and I had good reasons for the entries. 2 winners, 0 losers, and 0 break-even trades, good session! I missed a trade opportunity around 11:24, but I hesitated because 7 out of 8 bars were bull bars. I was thinking of entering short for a test of the EMA, hesitated and missed the opportunity.",

    trade1Header:"Trade 1 short, hit +8-pip target",
    reasonToTakeTrade1: "Reason to enter: Rejection at previous resistance levels (swing highs) and a bull flag after a wedge (3 pushes up). ",
    trade1: "I did not enter early and I waited for failure by the bulls to push the market up, I entered with limit orders and waited to get filled. My stop loss was one pip above the tails so I had a R:R of 1:2 on this trade. The scalp too 2:57 minutes and was not even close to my stop. I set my target to close the EMA gap in a pullback in a bear trend, price was vacuumed down to EMA.",

    trade2Header:"Trade 2, short, hit +8-pip target",
    reasonToTakeTrade2: "Reason to enter: Early entry, vacuum into previous strong selling.",
    trade2: "I entered a little early and should have waited for more information before taking the trade (see this in hindsight) I took the trade because I was expecting another bear leg down and there was a buy climax into previous strong selling and up to EMA. The R:R was 5:8 so almost a 1:2 risk/reward. My target was one pip above the open of the bull climax bar.",

    trade3Header:"",
    reasonToTakeTrade3: "",
    trade3: "",

    trade4Header:"",
    reasonToTakeTrade4: "",
    trade4: "",

    trade5Header: "",
    reasonToTakeTrade5: "",
    trade5: "",

    trade6Header:"",
    reasonToTakeTrade6: "",
    trade6: "",

    trade7Header:"",
    reasonToTakeTrade7: "",
    trade7: "",

    trade8Header:"",
    reasonToTakeTrade8: "",
    trade8: "",

    trade9Header:"",
    reasonToTakeTrade9: "",
    trade9: "",

    trade10Header:"",
    reasonToTakeTrade10: "",
    trade10: "",

    trade11Header:"",
    reasonToTakeTrade11: "",
    trade11: "",

    trade12Header:"",
    reasonToTakeTrade12: "",
    trade12: "",

    trade13Header:"",
    reasonToTakeTrade13: "",
    trade13: "",

    trade14Header:"",
    reasonToTakeTrade14: "",
    trade14: "",

    trade15Header:"",
    reasonToTakeTrade15: "",
    trade15: "",

    trade16Header:"",
    reasonToTakeTrade16: "",
    trade16: "",

    trade17Header:"",
    reasonToTakeTrade17: "",
    trade17: "",
  },
];