export const blogList = [
  {
    id: 1,
    authorName: 'TraderBrunotte',
    authorAvatar: '/assets/images/authorStefanBlack.png',
    
    instrumentCoverImage: '/assets/images/ES/17012023_Tuesday_ES0323.jpg',
    tradingDate: 'Tuesday January 17, 2023',
    title: 'ES 03-23 | Tuesday 17:25-18:55 | +4,25 points ',
    category: 'ES',
    subCategory: ['ES 03-23'],

    numOfTrades: "7",
    totalPoints: "4,25",
    totalTicks: "17",
    winners: "4 (4 points)",
    losers: "2 (2,75 points)",
    breakEven: "1 (0,25 points)",
    NumOfTarget: "4 out of 7",

    tradeDescription: "This is the first session where I have traded with my new 1-tick scalping method. The basic setup is that I enter the market after and on the close of a trigger bar. I always need a signal bar that closes within the 75% upper range in an uptrend or closes within the lower 25% of the signal bar range. I may only enter if the signal bar is a 100% high-, or low-closing bar, if this happens I may enter early and take a chance.",
    summary: "The lesson to be learned from this session is that I can take a chance and enter at the close of a strong signal bar closing on its high or low (100%)! The bulls/bears are clearly in control and there is a high probability of at least 1 point up/down on the trigger bar. This is the only time I may enter with a signal bar! I would have made 5 winners and 2 losers if I had entered long on the high closing 100% bull signal bars and low closing 100% bear signal bars.",
    trade1: "TRADE 2 - Long + 1 point - Market was in an uptrend after breaking and closing above the swing high, there was a small pullback with a strong signal bar (closing on its high - 100%). I entered at the close of the trigger bar and got filled straight away. The market quickly rallied up to my target for a 1 tick profit with a very small risk! This was a good trade where I waited for the market context to change from down to up and I entered at the close of the trigger bar, all according to the scalping method.",
    trade2: "TRADE 3 - Long – 1 point - The market gave another strong signal bar (closing on its high -100%). I missed the entry at the trigger bar high but went long a little bit lower, I got scared and moved my stop closer and got stopped out by 2 ticks, should have waited for the bear bar to close and then trail my stop!",
    trade3: "TRADE 4 - Long +0,25 points - The market gave another great signal bar (closing on its high -100%). The market touched my target and my trailing stop was triggered and was moved to break-even +1, I didn’t get filled at target and I was stopped out. This trade was just bad luck, target should have been reached but there were strong bears that tested the bulls.",
    trade4: "TRADE 5 - Long +1 point - I entered at the close of the trigger bar after the market gave me a weaker signal bar (80%). Target was reached and it tested the previous high of the bear leg down before the session start. This was also the high of my session.",
    trade5: "TRADE 6 - Short -1,75 points - The market gave me two weak bear signal bars, but the move down was strong. I entered short after bear trend confirmation (close below previous swing low) and was stopped out almost at my full stop (8 ticks). I should have waited for the pullback before entering the market, there was a strong leg down and I entered at the end of the first leg down (should have waited).",
    trade6: "TRADE 8 - Short + 1 point - The doji bar was the signal bar (80%), I entered short at the close of the trigger bar. The trade was a bit long (1:43 min) because the bulls tried to push the market back up. This was a good trade because the probability of more down was high after the strong first bear leg down.",
    trade7: "TRADE 7 - Long + 1 point - This was a counter trend long after a strong bull signal bar (100%) I was filled after the close of the trigger bar (which ended up as another strong signal bar 100%). I reached target after 1:12 seconds.",
    trade8: "",
    trade9: "",
    trade10: "",
    trade11: "",
    trade12: "",
    trade13: "",
    trade14: "",
    trade15: "",
    trade16: "",
    trade17: "",
  },
];